In [3]:
import numpy as np

In [5]:
arr = np.array([1,2,3,4])
print(arr)


[1 2 3 4]


In [6]:
#zero arrays
za = np.zeros((3,3))
print(za)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


#one arrays
oa = np.ones((9,9))
print(oa)

In [13]:
#arrange function
arange = np.arange(1,10,2)
print(arange)

[1 3 5 7 9]


In [21]:
#linspace - evenly spaced values in a range
ar = np.linspace(0,0.1,4)
print(ar)

[0.         0.03333333 0.06666667 0.1       ]


In [24]:
la1 = np.array([1,2,3])
la2 = np.array([2,3,4])
print(la1 + la2)

[3 5 7]
